/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.48
 * Generated at: 2021-10-19 02:33:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/resources/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function list(page) {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/list.do\",\r\n");
      out.write("			type : \"GET\",\r\n");
      out.write("			data : {\r\n");
      out.write("				page : page,\r\n");
      out.write("				type : $(\"#type option:selected\").val(),\r\n");
      out.write("				keyword : $(\"#keyword\").val()\r\n");
      out.write("			},\r\n");
      out.write("			dataType : \"JSON\",\r\n");
      out.write("\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				console.log(result.list);\r\n");
      out.write("				$(\"#tbody\").empty();\r\n");
      out.write("				$(\"#paging\").empty();\r\n");
      out.write("				var list = result.list;\r\n");
      out.write("				for (var i = 0; i < list.length; i++) {\r\n");
      out.write("					var html = \"<tr>\"\r\n");
      out.write("					html += \"<td>\" + list[i].bnum + \"</td>\"\r\n");
      out.write("					html += \"<td><a href='detail.do?bnum=\" + list[i].bnum\r\n");
      out.write("							+ \"'>\" + list[i].title + \"</a></td>\"\r\n");
      out.write("					html += \"<td>\" + list[i].writer + \"</td>\"\r\n");
      out.write("					html += \"<td>\" + list[i].bdate + \"</td>\"\r\n");
      out.write("					html += \"<td>\" + list[i].bcnt + \"</td>\"\r\n");
      out.write("					//html += \"<td>\" + list[i].bcontent + \"</td>\"\r\n");
      out.write("					html += \"<td>\" + list[i].btype + \"</td>\"\r\n");
      out.write("					$(\"#tbody\").append(html)\r\n");
      out.write("				}\r\n");
      out.write("				if (result.prev) {\r\n");
      out.write("					$(\"#paging\").append(\r\n");
      out.write("							\"<button onclick=list(\" + Number(page - 1)\r\n");
      out.write("									+ \")>이전</button>\");\r\n");
      out.write("				}\r\n");
      out.write("				for (var i = result.startPage; i <= result.endPage; i++) {\r\n");
      out.write("					$(\"#paging\").append(\r\n");
      out.write("							\"<button onclick=list(\" + i + \")>\" + i\r\n");
      out.write("									+ \"</button>\")\r\n");
      out.write("				}\r\n");
      out.write("				if (result.next) {\r\n");
      out.write("					$(\"#paging\").append(\r\n");
      out.write("							\"<button onclick=list(\" + Number(page + 1)\r\n");
      out.write("									+ \")>다음</button>\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("		list(1)\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"sb-nav-fixed\">\r\n");
      out.write("\r\n");
      out.write("	<!-- nav바 -->\r\n");
      out.write("	<nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("		<!-- Navbar Brand-->\r\n");
      out.write("		<a class=\"navbar-brand ps-3\" href=\"/home.do\">게시판 커뮤니티</a>\r\n");
      out.write("		<!-- Navbar-->\r\n");
      out.write("		<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("			<li class=\"nav-item dropdown\"><a\r\n");
      out.write("				class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\"\r\n");
      out.write("				role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i\r\n");
      out.write("					class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("					aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#!\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님\r\n");
      out.write("							안녕하세요.</a></li>\r\n");
      out.write("\r\n");
      out.write("					<li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"/logout.do\">Logout</a></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"userUpdate.do\">회원정보수정</a></li>\r\n");
      out.write("				</ul></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- nav바 -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 사이드nav바 -->\r\n");
      out.write("	<div id=\"layoutSidenav\">\r\n");
      out.write("		<div id=\"layoutSidenav_nav\">\r\n");
      out.write("			<nav class=\"sb-sidenav accordion sb-sidenav-dark\"\r\n");
      out.write("				id=\"sidenavAccordion\">\r\n");
      out.write("				<div class=\"sb-sidenav-menu\">\r\n");
      out.write("					<div class=\"nav\">\r\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">MENU</div>\r\n");
      out.write("						<a class=\"nav-link\" href=\"home.do\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-tachometer-alt\"></i>\r\n");
      out.write("							</div> HOME\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">MENU</div>\r\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("							data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\"\r\n");
      out.write("							aria-controls=\"collapseLayouts\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-columns\"></i>\r\n");
      out.write("							</div> link\r\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts\"\r\n");
      out.write("							aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("								<a class=\"nav-link\" href=\"insert.do\">새글작성</a>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"collapse\" id=\"collapsePages\"\r\n");
      out.write("							aria-labelledby=\"headingTwo\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav accordion\"\r\n");
      out.write("								id=\"sidenavAccordionPages\">\r\n");
      out.write("								<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\r\n");
      out.write("									data-bs-target=\"#pagesCollapseAuth\" aria-expanded=\"false\"\r\n");
      out.write("									aria-controls=\"pagesCollapseAuth\"> Authentication\r\n");
      out.write("									<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("										<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a> <a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#pagesCollapseError\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"pagesCollapseError\">\r\n");
      out.write("									Error\r\n");
      out.write("									<div class=\"sb-sidenav-collapse-arrow\">\r\n");
      out.write("										<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 사이드nav바 -->\r\n");
      out.write("\r\n");
      out.write("						<a class=\"nav-link\" href=\"home.do\">\r\n");
      out.write("							<div class=\"sb-nav-link-icon\">\r\n");
      out.write("								<i class=\"fas fa-table\"></i>\r\n");
      out.write("							</div> Tables\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sb-sidenav-footer\">\r\n");
      out.write("					<div class=\"small\">창윤코딩교실</div>\r\n");
      out.write("					게시판 커뮤니티\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"layoutSidenav_content\">\r\n");
      out.write("			<main>\r\n");
      out.write("				<div class=\"container-fluid px-4\">\r\n");
      out.write("					<ol class=\"breadcrumb mb-4\">\r\n");
      out.write("						<li class=\"breadcrumb-item active\">Tables</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<fieldset>\r\n");
      out.write("\r\n");
      out.write("								<select id=\"type\">\r\n");
      out.write("									<option value=\"title\">제목</option>\r\n");
      out.write("									<option value=\"writer\">저자</option>\r\n");
      out.write("									<option value=\"bcontent\">내용</option>\r\n");
      out.write("									<option value=\"bdate\">날짜</option>\r\n");
      out.write("								</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<label>검색</label> <input id=\"keyword\" class=\"form-control\"\r\n");
      out.write("									type=\"text\" placeholder=\"Search for...\"\r\n");
      out.write("									aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\r\n");
      out.write("								<button type=\"button\" onclick=\"list(1)\">검색</button>\r\n");
      out.write("								<button type=\"button\" onclick=\"location.href='insert.do'\">새글작성</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						</fieldset>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card mb-4\">\r\n");
      out.write("						<div class=\"card-header\">\r\n");
      out.write("							<i class=\"fas fa-table me-1\"></i> 글목록\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<table id=\"datatablesSimple\" border=\"1\" width=\"70%\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>글번호</td>\r\n");
      out.write("										<td>제목</td>\r\n");
      out.write("										<td>작성자</td>\r\n");
      out.write("										<td>작성일</td>\r\n");
      out.write("										<td>조회</td>							\r\n");
      out.write("										<td>분류</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tfoot>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>글번호</td>\r\n");
      out.write("										<td>제목</td>\r\n");
      out.write("										<td>작성자</td>\r\n");
      out.write("										<td>작성일</td>\r\n");
      out.write("										<td>조회</td>									\r\n");
      out.write("										<td>분류</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</tfoot>\r\n");
      out.write("								<tbody id=\"tbody\"></tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("							<div id=\"paging\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</main>\r\n");
      out.write("			<footer class=\"py-4 bg-light mt-auto\">\r\n");
      out.write("				<div class=\"container-fluid px-4\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"d-flex align-items-center justify-content-between small\">\r\n");
      out.write("					\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"https://youtube.com/\">youtube</a> &middot; <a\r\n");
      out.write("								href=\"https://naver.com/\"> NAVER</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</footer>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"/resources/js/scripts.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- 	<script src=\"/resources/js/datatables-simple-demo.js\"></script>  -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
